name: gps
bootstrap:
  http_server:
    port: 8081
  data_source:
    debug: true
    user: "postgres"
    password: "123456"
    host: "localhost"
    port: "5432"
    db_name: "gps"
  elastic_search:
    addresses: ["", ""]
    username: "elastic"
    password: "123456"
  kafka:
    url: "localhost"
    sasl_enable: false
    user: ""
    password: ""
    mechanism: "plain"
  redis:
    addrs: "localhost"
    password: redis_123
